name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Prepare node
        uses: actions/setup-node@v2.5.0
        with:
          node-version-file: ".nvmrc"

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install imagemagick -y --no-install-recommends
          npm install -g netlify-cli

      - name: Install node packages
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify deploy --dir=dist --prodIfUnlocked

